### ISSUE TITLE
NameError: uninitialized constant AWS

### ISSUE THREAD

**Issue by itay-grudev** [lserman/capistrano-elbas#26]
```ruby
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
cap aborted!
NameError: uninitialized constant AWS
Did you mean?  Aws
```
```
/Users/me/.rvm/gems/ruby-2.3.4/gems/elbas-0.0.4/lib/elbas/capistrano.rb:24:in `autoscaling'
/Users/me/.rvm/gems/ruby-2.3.4/gems/elbas-0.0.4/lib/elbas/capistrano.rb:9:in `autoscale'
config/deploy/production.rb:4:in `<top (required)>'
/Users/me/.rvm/gems/ruby-2.3.4/gems/capistrano-3.7.2/lib/capistrano/setup.rb:28:in `load'
/Users/me/.rvm/gems/ruby-2.3.4/gems/capistrano-3.7.2/lib/capistrano/setup.rb:28:in `block (3 levels) in <top (required)>'
/Users/me/.rvm/gems/ruby-2.3.4/gems/capistrano-3.7.2/lib/capistrano/configuration/variables.rb:32:in `untrusted!'
/Users/me/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
/Users/me/.rvm/gems/ruby-2.3.4/gems/capistrano-3.7.2/lib/capistrano/setup.rb:26:in `block (2 levels) in <top (required)>'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/me/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/me/.rvm/gems/ruby-2.3.4/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/Users/me/.rvm/gems/ruby-2.3.4/gems/capistrano-3.7.2/lib/capistrano/application.rb:14:in `run'
/Users/me/.rvm/gems/ruby-2.3.4/gems/capistrano-3.7.2/bin/cap:3:in `<top (required)>'
/Users/me/.rvm/gems/ruby-2.3.4/bin/cap:23:in `load'
/Users/me/.rvm/gems/ruby-2.3.4/bin/cap:23:in `<main>'
/Users/me/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/Users/me/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => production
```

**Comment by itay-grudev** [comment]
`aws-sdk` no longer has a dependency on `gem 'aws-sdk-v1'` and it seems like you guys are using the old API. 

Adding:
```ruby
gem 'aws-sdk-v1'
```
to my `Gemfile` and then `bundle install` or `bundle update` (to resolve conflicts) worked for me. But I reckon updating the gem to use the new AWS API would be better.

**Comment by lserman** [comment]
I'll no longer be maintaining ELBAS <3, which relies on SDK v1. New version relies on SDK v3, so this shouldn't be a problem in the versions I'm interested in maintaining.
